#!/bin/bash

# Periodic jobs are triggered by a configurable timer, by default they run daily
# and use the latest commit to the branch being tested.

# post is an optional executable that is the last stage to run. It is used to
# perform actions that make use of the data generated. Such actions include log
# aggregation and preparing the node to be used as an image.

# Environment variables
# RE_HOOK_ARTIFACT_DIR: The directory where job artifacts (log files,
# configuration used, etc) should be written.
# RE_HOOK_RESULT_DIR: The directory where test results should be written.
# RE_JOB_NAME: The name of the job itself. For example
# PM_repo-name-series-image-scenario-action
# RE_JOB_IMAGE: The name of the 'image' as defined in the job.
# RE_JOB_SCENARIO: The name of the 'scenario' as defined in the job.
# RE_JOB_ACTION: The name of the 'action' as defined in the job.
# RE_JOB_FLAVOR: The name of the 'flavor' as defined in the job.
# RE_JOB_TRIGGER: The name of the 'trigger' that initiated the build, examples
# include 'PULL', 'PUSH', 'TIMER' and 'OTHER'.
# RE_JOB_TRIGGER_DETAIL: Provides additional information regarding the job
# trigger.
# RE_JOB_REPO_NAME: The project's GitHub repository which gets cloned in the
# job. For example, for the repository found at
# https://github.com/rcbops/rpc-gating, the name is rpc-gating.