#!/bin/bash

# Periodic jobs are triggered by a configurable timer, by default they run daily
# and use the latest commit to the branch being tested.

# pre is an optional executable for preparing the node prior to running the
# build. This step is retried on failure given that it performs preparatory
# actions and not the actual function of the job. Examples of actions that
# should be taken here include things that would be performed manually such as
# setting configuration options.

# Environment variables
# RE_HOOK_ARTIFACT_DIR: The directory where job artifacts (log files,
# configuration used, etc) should be written.
# RE_HOOK_RESULT_DIR: The directory where test results should be written.
# RE_JOB_NAME: The name of the job itself. For example
# PM_repo-name-series-image-scenario-action
# RE_JOB_IMAGE: The name of the 'image' as defined in the job.
# RE_JOB_SCENARIO: The name of the 'scenario' as defined in the job.
# RE_JOB_ACTION: The name of the 'action' as defined in the job.
# RE_JOB_FLAVOR: The name of the 'flavor' as defined in the job.
# RE_JOB_TRIGGER: The name of the 'trigger' that initiated the build, examples
# include 'PULL', 'PUSH', 'TIMER' and 'OTHER'.
# RE_JOB_TRIGGER_DETAIL: Provides additional information regarding the job
# trigger.
# RE_JOB_REPO_NAME: The project's GitHub repository which gets cloned in the
# job. For example, for the repository found at
# https://github.com/rcbops/rpc-gating, the name is rpc-gating.

# If the current folder's basename is osp-mnaio then we assume
# that it is the root of the git clone. If the git clone is not in
# /opt then we symlink the current folder there so that all the
# osp-mnaio scripts work as expected.
if [[ "$(basename ${PWD})" == "osp-mnaio" ]]; then
  if [[ "${PWD}" != "/opt/osp-mnaio" ]]; then
    ln -sfn ${PWD} /opt/osp-mnaio
  fi
fi

# We need to ensure that we use the rackspace mirrors, as they are
# most reliable. We also need to ensure that python and the python
# yaml library are present for ansible to work.
source "$(readlink -f $(dirname ${0}))/../gating_prerequisites.sh"
