#!/bin/bash

# Periodic jobs are triggered by a configurable timer, by default they run daily
# and use the latest commit to the branch being tested.

# run is a required executable that executes the purpose of the job. For
# example, if the project deploys some software, this file would be used to
# perform the deployment and then test the success of the operation.

# Environment variables
# RE_HOOK_ARTIFACT_DIR: The directory where job artifacts (log files,
# configuration used, etc) should be written.
# RE_HOOK_RESULT_DIR: The directory where test results should be written.
# RE_JOB_NAME: The name of the job itself. For example
# PM_repo-name-series-image-scenario-action
# RE_JOB_IMAGE: The name of the 'image' as defined in the job.
# RE_JOB_SCENARIO: The name of the 'scenario' as defined in the job.
# RE_JOB_ACTION: The name of the 'action' as defined in the job.
# RE_JOB_FLAVOR: The name of the 'flavor' as defined in the job.
# RE_JOB_TRIGGER: The name of the 'trigger' that initiated the build, examples
# include 'PULL', 'PUSH', 'TIMER' and 'OTHER'.
# RE_JOB_TRIGGER_DETAIL: Provides additional information regarding the job
# trigger.
# RE_JOB_REPO_NAME: The project's GitHub repository which gets cloned in the
# job. For example, for the repository found at
# https://github.com/rcbops/rpc-gating, the name is rpc-gating.

set -exu

source "$(readlink -f $(dirname ${0}))/../env_vars"

if [ "${OSP_JOB_ACTION}" = "deploy-smoke-tests" ]; then
    export TEMPEST_TESTS='--smoke --blacklist-file /home/stack/tempest-blacklist.txt'
elif [ "${OSP_JOB_ACTION}" = "deploy-full-tests" ]; then
    # NOTE(coreywright): Explicitly specify the regex that matches all tests.
    # Technically executing Tempest without specifying any tests causes it to
    # run all tests, but between our use of an env var and Bash not always
    # distinguishing between an env var that's unset and one that's set to
    # null, explicitly specify all tests so the default test regex in build.sh
    # doesn't get used.
    export TEMPEST_TESTS='--regex ^.*$ --blacklist-file /home/stack/tempest-blacklist.txt'
elif [ "${OSP_JOB_ACTION}" = "deploy-system-tests" ]; then
    export TEMPEST_TESTS=''
else
    echo "ERROR: unhandled OSP_JOB_ACTION value: \"${OSP_JOB_ACTION}\""
    exit 1
fi

# start the osp-mnaio build
pushd /opt/osp-mnaio
  ./build.sh
popd

if [ "${OSP_JOB_ACTION}" = "deploy-system-tests" ]; then
    bash -c "$(readlink -f $(dirname ${0})/run_system_tests.sh)"
fi
