#!/bin/bash

# Gate jobs are triggered by a comment on a pull request. The change is merged
# automatically if all the tests pass. The gate job ensures that changes are
# tested against the state of the target branch when the code is merged. In
# comparison, check jobs test against the state of the branch when the test is
# started.

# run is a required executable that executes the purpose of the job. For
# example, if the project deploys some software, this file would be used to
# perform the deployment and then test the success of the operation.

# Environment variables
# RE_HOOK_ARTIFACT_DIR: The directory where job artifacts (log files,
# configuration used, etc) should be written.
# RE_HOOK_RESULT_DIR: The directory where test results should be written.
# RE_JOB_NAME: The name of the job itself. For example
# PM_repo-name-series-image-scenario-action
# RE_JOB_IMAGE: The name of the 'image' as defined in the job.
# RE_JOB_SCENARIO: The name of the 'scenario' as defined in the job.
# RE_JOB_ACTION: The name of the 'action' as defined in the job.
# RE_JOB_FLAVOR: The name of the 'flavor' as defined in the job.
# RE_JOB_TRIGGER: The name of the 'trigger' that initiated the build, examples
# include 'PULL', 'PUSH', 'TIMER' and 'OTHER'.
# RE_JOB_TRIGGER_DETAIL: Provides additional information regarding the job
# trigger.
# RE_JOB_REPO_NAME: The project's GitHub repository which gets cloned in the
# job. For example, for the repository found at
# https://github.com/rcbops/rpc-gating, the name is rpc-gating.