#!/bin/bash

# Check jobs are triggered when a pull request is created. Any job can be added
# as a check, the most common use is for lint, unit and basic functional tests.

# post is an optional executable that is the last stage to run. It is used to
# perform actions that make use of the data generated. Such actions include log
# aggregation and preparing the node to be used as an image.

# Environment variables
# RE_HOOK_ARTIFACT_DIR: The directory where job artifacts (log files,
# configuration used, etc) should be written.
# RE_HOOK_RESULT_DIR: The directory where test results should be written.
# RE_JOB_NAME: The name of the job itself. For example
# PM_repo-name-series-image-scenario-action
# RE_JOB_IMAGE: The name of the 'image' as defined in the job.
# RE_JOB_SCENARIO: The name of the 'scenario' as defined in the job.
# RE_JOB_ACTION: The name of the 'action' as defined in the job.
# RE_JOB_FLAVOR: The name of the 'flavor' as defined in the job.
# RE_JOB_TRIGGER: The name of the 'trigger' that initiated the build, examples
# include 'PULL', 'PUSH', 'TIMER' and 'OTHER'.
# RE_JOB_TRIGGER_DETAIL: Provides additional information regarding the job
# trigger.
# RE_JOB_REPO_NAME: The project's GitHub repository which gets cloned in the
# job. For example, for the repository found at
# https://github.com/rcbops/rpc-gating, the name is rpc-gating.

source "$(readlink -f $(dirname ${0}))/../env_vars"

set -xv

RESULTS_DIR=/buildlogs

# unregister director node from rhn
pushd /opt/osp-mnaio
  ansible -i playbooks/inventory/hosts deploy_hosts -m shell -a "subscription-manager unregister"
popd

# generate log directories
mkdir -p ${RESULTS_DIR}/{ara,director}

# generate ara html report
ara generate html ${RESULTS_DIR}/ara/

# grab deploy logs from director
scp -p stack@director:/home/stack/logs/*.log ${RESULTS_DIR}/director/

# grab instack log from director
scp -p stack@director:/home/stack/.instack/install-undercloud.log \
       ${RESULTS_DIR}/director/instack-install-undercloud.log

# grab tempest log from director
scp -p stack@director:/home/stack/tempest/tempest.log \
       ${RESULTS_DIR}/director/

# grab tempest blacklist from director
scp -p stack@director:/home/stack/tempest-blacklist.txt \
       ${RESULTS_DIR}/director/

# grab OpenStack service logs from overcloud nodes
pushd /opt/osp-mnaio
  ansible-playbook -i playbooks/inventory/hosts playbooks/collect-logs.yml \
                   -e redhat_osp_version=${REDHAT_OSP_VERSION} \
                   -e log_dir=${RESULTS_DIR}
popd

# rename log file extension from "log" to "txt", as "txt" maps to a recognized
# MIME type, for viewing within the browser in the web-based artifact interface
find ${RESULTS_DIR} -type f -name '*.log' \
     -exec bash -c 'mv -v "${1}" "${1/%.log/.txt}"' - '{}' \;
