#!/bin/bash

# Check jobs are triggered when a pull request is created. Any job can be added
# as a check, the most common use is for lint, unit and basic functional tests.

# run is a required executable that executes the purpose of the job. For
# example, if the project deploys some software, this file would be used to
# perform the deployment and then test the success of the operation.

# Environment variables
# RE_HOOK_ARTIFACT_DIR: The directory where job artifacts (log files,
# configuration used, etc) should be written.
# RE_HOOK_RESULT_DIR: The directory where test results should be written.
# RE_JOB_NAME: The name of the job itself. For example
# PM_repo-name-series-image-scenario-action
# RE_JOB_IMAGE: The name of the 'image' as defined in the job.
# RE_JOB_SCENARIO: The name of the 'scenario' as defined in the job.
# RE_JOB_ACTION: The name of the 'action' as defined in the job.
# RE_JOB_FLAVOR: The name of the 'flavor' as defined in the job.
# RE_JOB_TRIGGER: The name of the 'trigger' that initiated the build, examples
# include 'PULL', 'PUSH', 'TIMER' and 'OTHER'.
# RE_JOB_TRIGGER_DETAIL: Provides additional information regarding the job
# trigger.
# RE_JOB_REPO_NAME: The project's GitHub repository which gets cloned in the
# job. For example, for the repository found at
# https://github.com/rcbops/rpc-gating, the name is rpc-gating.

set -exu

## Display environment
echo "+-------------------- ENV VARS --------------------+"
env
echo "+-------------------- ENV VARS --------------------+"

## Vars ----------------------------------------------------------------------
export OSP_DEPLOY_VERSION=`echo ${RE_JOB_ACTION} | awk -F'_' {'print $2'}`
export OSP_JOB_ACTION=`echo ${RE_JOB_ACTION} | awk -F'_' {'print $3'}`
export REDHAT_USERNAME=${RPC_OSP_REDHAT_USERNAME:-''}
export REDHAT_PASSWORD=${RPC_OSP_REDHAT_PASSWORD:-''}
export REDHAT_POOL_ID=${RPC_OSP_REDHAT_POOL_ID:-''}
export REDHAT_ISO_URL=${RPC_OSP_REDHAT_ISO_URL:-''}
export REDHAT_CONSUMER_NAME="osp-mnaio-PR-test"
export REDHAT_OSP_VERSION=${OSP_DEPLOY_VERSION:-'13'}
export REDHAT_OVERCLOUD_REGISTER="false"

# start the osp-mnaio build
pushd /opt/osp-mnaio
  ./build.sh
popd
