---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in witing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Test deployed cloud
  hosts: deploy_hosts
  gather_facts: "{{ gather_facts | default(true) }}"
  environment: "{{ deployment_environment_variables | default({}) }}"
  remote_user: stack
  become: yes
  tags:
    - test-osp
  tasks:
    - name: Gather variables for each operating system
      include_vars: "{{ item }}"
      with_first_found:
        - "{{ playbook_dir }}/vars/{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ playbook_dir }}/vars/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ playbook_dir }}/vars/{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ playbook_dir }}/vars/{{ ansible_distribution | lower }}.yml"
        - "{{ playbook_dir }}/vars/{{ ansible_os_family | lower }}.yml"
      tags:
        - always

    - name: Copy tempest script to director
      template:
        src: "osp/{{ redhat_osp_version }}/overcloud/overcloud-test.sh.j2"
        dest: "/home/stack/scripts/overcloud-test.sh"
        owner: "stack"
        group: "stack"
        mode: "0754"

    - name: Copy tempest blacklist to director
      template:
        src: "osp/{{ redhat_osp_version }}/overcloud/tempest-blacklist.txt.j2"
        dest: "/home/stack/tempest-blacklist.txt"
        owner: "stack"
        group: "stack"
        mode: "0644"

    - name: Run tempest script on director
      shell: |
        set -o pipefail
        bash /home/stack/scripts/overcloud-test.sh \
        2>&1 | tee /home/stack/logs/overcloud_test.log
      args:
        chdir: /home/stack
      become_user: stack
